### ISSUE TITLE
Option to replace double quote by single quote

### ISSUE THREAD

**Issue by jormabs** [jakearchibald/svgomg#133]
Hi, I would like there to be an option to replace the double quotes, with single quotes. Very useful to include as content within CSS.

**Double-quoted (syntax error)**

```css
.my-class::after{
  content: url("data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" viewBox="0 0 512 512"><path d="M255 0C114.06 0 0 114.05"/></svg>");
}
```

**Single-quoted (no erros)**

```css
.my-class::after{
  content: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='0 0 512 512'><path d='M255 0C114.06 0 0 114.05'/></svg>");
}
```
