### ISSUE TITLE
Preview on vivid background button tweaks

### ISSUE THREAD

**Issue by XhmikosR** [jakearchibald/svgomg#312]
1. would be nice to have a different color when the button is active. Something like this will probably do the job:
  ```scss
  .minor-floating-action-button {
    // ...
    &.active {
      background-color: #00bcd4;
      color: #fff;
    }
  }
  ```
2. the button title should ideally change to reflect which option is currently active, i.e. "Preview on vivid background" or "Preview on light (?) background"
